version: '3.1'

services:
  postgres:
    image: postgres:9.6
    ports:
      - "5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: andre
      POSTGRES_DB: itineraries

volumes:
  microservices_devdojo:
