server:
  port: 8082

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://service-discovery:8081/eureka/
    register-with-eureka: true

spring:
  application:
    name: itinerary
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        jdbc:
          lob:
            non_contextual_creation: true
  jmx:
    enabled: false
  datasource:
    url: jdbc:postgresql://postgres:5432/itineraries
    username: postgres
    password: andre

auth:
  header: Authorization
  secret: bHEGcbFS9pkpQrZMweV4K6VVSlea8xbFyZDWOpt4ntQcJYOXIULIogCpMfP3OtD1
  prefix: Bearer 
  expires: 604800