INSERT INTO users (id,email,name,password,password_resetuuid,username,role_id) VALUES (1,'user@adidas.com',NULL,'$2a$10$ZGgOdPaEXTwoHzvjz/i5ieRH60pWXO.OO3QwyiGapnTtuWGfRxcWe',NULL,'adidas',NULL);

INSERT INTO cities (id,name,x,y) VALUES (1,'Mertzfurt',3,11);
INSERT INTO cities (id,name,x,y) VALUES (2,'East Carrolshire',4,4);
INSERT INTO cities (id,name,x,y) VALUES (3,'Simonisbury',11,9);
INSERT INTO cities (id,name,x,y) VALUES (4,'Lake Wendellstad',2,6);
INSERT INTO cities (id,name,x,y) VALUES (5,'Runteview',12,7);
INSERT INTO cities (id,name,x,y) VALUES (6,'Gearldineshire',5,12);
INSERT INTO cities (id,name,x,y) VALUES (7,'Jodyberg',9,15);
INSERT INTO cities (id,name,x,y) VALUES (8,'South Ismaelburgh',8,9);
INSERT INTO cities (id,name,x,y) VALUES (9,'Port Alfonso',12,14);
INSERT INTO cities (id,name,x,y) VALUES (10,'Rosemaryberg',6,12);
INSERT INTO cities (id,name,x,y) VALUES (11,'Pfefferside',15,15);
INSERT INTO cities (id,name,x,y) VALUES (12,'North Joshuaville',9,12);
INSERT INTO cities (id,name,x,y) VALUES (13,'Deangeloton',2,1);
INSERT INTO cities (id,name,x,y) VALUES (14,'Camillahaven',5,9);
INSERT INTO cities (id,name,x,y) VALUES (15,'Grimesland',9,2);
INSERT INTO cities (id,name,x,y) VALUES (16,'Darceyport',6,9);
INSERT INTO cities (id,name,x,y) VALUES (17,'Sterlingburgh',7,5);
INSERT INTO cities (id,name,x,y) VALUES (18,'McLaughlinbury',7,7);
INSERT INTO cities (id,name,x,y) VALUES (19,'Sulemaville',2,3);
INSERT INTO cities (id,name,x,y) VALUES (20,'Yundtmouth',11,13);
INSERT INTO cities (id,name,x,y) VALUES (21,'Bergetown',10,6);
INSERT INTO cities (id,name,x,y) VALUES (22,'South Scottyshire',14,9);
INSERT INTO cities (id,name,x,y) VALUES (23,'Shanefurt',10,6);
INSERT INTO cities (id,name,x,y) VALUES (24,'New Mel',1,10);
INSERT INTO cities (id,name,x,y) VALUES (25,'Cronaborough',1,14);
INSERT INTO cities (id,name,x,y) VALUES (26,'South Dyan',12,1);
INSERT INTO cities (id,name,x,y) VALUES (27,'Kovacekside',4,6);
INSERT INTO cities (id,name,x,y) VALUES (28,'New Owenburgh',6,13);
INSERT INTO cities (id,name,x,y) VALUES (29,'Franeckibury',9,3);
INSERT INTO cities (id,name,x,y) VALUES (30,'Port Davis',5,14);
INSERT INTO cities (id,name,x,y) VALUES (31,'Port Koriville',1,6);
INSERT INTO cities (id,name,x,y) VALUES (32,'Schusterchester',3,15);
INSERT INTO cities (id,name,x,y) VALUES (33,'North Lennie',1,1);
INSERT INTO cities (id,name,x,y) VALUES (34,'Cruickshankland',10,1);
INSERT INTO cities (id,name,x,y) VALUES (35,'Eleanorfurt',1,10);
INSERT INTO cities (id,name,x,y) VALUES (36,'Frankfort',2,13);
INSERT INTO cities (id,name,x,y) VALUES (37,'Rodville',9,10);
INSERT INTO cities (id,name,x,y) VALUES (38,'Lake Dylanview',7,1);
INSERT INTO cities (id,name,x,y) VALUES (39,'Pamouth',6,3);
INSERT INTO cities (id,name,x,y) VALUES (40,'South Anikatown',6,10);
INSERT INTO cities (id,name,x,y) VALUES (41,'Port Noriko',6,1);
INSERT INTO cities (id,name,x,y) VALUES (42,'North Olene',9,15);
INSERT INTO cities (id,name,x,y) VALUES (43,'Trantowland',15,5);
INSERT INTO cities (id,name,x,y) VALUES (44,'East Hershel',3,3);
INSERT INTO cities (id,name,x,y) VALUES (45,'Darrenhaven',5,8);
INSERT INTO cities (id,name,x,y) VALUES (46,'Port Isishaven',15,7);
INSERT INTO cities (id,name,x,y) VALUES (47,'East Winterside',11,11);
INSERT INTO cities (id,name,x,y) VALUES (48,'Hilpertside',10,15);
INSERT INTO cities (id,name,x,y) VALUES (49,'South Kathlinetown',8,3);
INSERT INTO cities (id,name,x,y) VALUES (50,'Gerholdchester',9,14);
